import Head from 'next/head'
import { getName, getTauriVersion, getVersion } from '@tauri-apps/api/app';
import { useState, useEffect, Suspense } from 'react';
import { invoke } from '@tauri-apps/api/tauri';

type AppState = {
  name: string;
}

export default function Home() {
  const [appState, setAppState] = useState<AppState | undefined>();
  useEffect(() => {
    if ( typeof window === 'undefined') return;
    (async () => {
      const name = await getName();
      const tv = await getTauriVersion();
      const v = await getVersion();
      const nameConcat = `${name}:${v}:${tv}`;
      setAppState({name: nameConcat});
      console.log('before invoke');
      const invResult: string = await invoke('custom_command', {input_msg: 'thing'});
      console.log('after invoke')
      setAppState({name: invResult});
    })();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Suspense fallback={<>Loading...</>}>
          {appState && <div>App name is {appState.name}</div>}
        </Suspense>
      </main>
    </>
  )
}
