import { Navbar, navigation } from './components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full overflow-hidden'>
      <body className='h-full'>
        <Navbar vals={navigation} depth={0} />
        {children}
      </body>
    </html>
  )
}
