import './globals.css'
import { APP_DISPLAY_NAME } from '@ozy/constants';
import { headers } from 'next/headers';
import { CurPath } from './components/CurPath';

export const metadata = {
  title: APP_DISPLAY_NAME,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const reqHeaders = headers();
  return (
    <html lang="en" className='h-full overflow-hidden'>
      <body className='h-full'>
        <pre className='absolute bottom-0'>
          <CurPath /><br />
          {reqHeaders.get('next-url')}
        </pre>
        {children}
      </body>
    </html>
  )
}
